//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaLogicaNegocios.ServicioMasterBikes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cl_Producto", Namespace="http://schemas.datacontract.org/2004/07/WcfMasterBikes.CapaAccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Cl_Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int aroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int descuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] imagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string proveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rutaFotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int aro {
            get {
                return this.aroField;
            }
            set {
                if ((this.aroField.Equals(value) != true)) {
                    this.aroField = value;
                    this.RaisePropertyChanged("aro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int descuento {
            get {
                return this.descuentoField;
            }
            set {
                if ((this.descuentoField.Equals(value) != true)) {
                    this.descuentoField = value;
                    this.RaisePropertyChanged("descuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                if ((this.idProductoField.Equals(value) != true)) {
                    this.idProductoField = value;
                    this.RaisePropertyChanged("idProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProveedor {
            get {
                return this.idProveedorField;
            }
            set {
                if ((this.idProveedorField.Equals(value) != true)) {
                    this.idProveedorField = value;
                    this.RaisePropertyChanged("idProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] imagen {
            get {
                return this.imagenField;
            }
            set {
                if ((object.ReferenceEquals(this.imagenField, value) != true)) {
                    this.imagenField = value;
                    this.RaisePropertyChanged("imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                if ((object.ReferenceEquals(this.modeloField, value) != true)) {
                    this.modeloField = value;
                    this.RaisePropertyChanged("modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string proveedor {
            get {
                return this.proveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.proveedorField, value) != true)) {
                    this.proveedorField = value;
                    this.RaisePropertyChanged("proveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rutaFoto {
            get {
                return this.rutaFotoField;
            }
            set {
                if ((object.ReferenceEquals(this.rutaFotoField, value) != true)) {
                    this.rutaFotoField = value;
                    this.RaisePropertyChanged("rutaFoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cl_Municipalidad", Namespace="http://schemas.datacontract.org/2004/07/WcfMasterBikes.CapaAccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Cl_Municipalidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idMunicipalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string municipalidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMunicipalidad {
            get {
                return this.idMunicipalidadField;
            }
            set {
                if ((this.idMunicipalidadField.Equals(value) != true)) {
                    this.idMunicipalidadField = value;
                    this.RaisePropertyChanged("idMunicipalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string municipalidad {
            get {
                return this.municipalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.municipalidadField, value) != true)) {
                    this.municipalidadField = value;
                    this.RaisePropertyChanged("municipalidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioMasterBikes.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ImgToByteArray", ReplyAction="http://tempuri.org/IServicio/ImgToByteArrayResponse")]
        byte[] ImgToByteArray(string ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ImgToByteArray", ReplyAction="http://tempuri.org/IServicio/ImgToByteArrayResponse")]
        System.Threading.Tasks.Task<byte[]> ImgToByteArrayAsync(string ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/obtenerProdProv", ReplyAction="http://tempuri.org/IServicio/obtenerProdProvResponse")]
        CapaLogicaNegocios.ServicioMasterBikes.Cl_Producto[] obtenerProdProv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/obtenerProdProv", ReplyAction="http://tempuri.org/IServicio/obtenerProdProvResponse")]
        System.Threading.Tasks.Task<CapaLogicaNegocios.ServicioMasterBikes.Cl_Producto[]> obtenerProdProvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/obtenerProductos", ReplyAction="http://tempuri.org/IServicio/obtenerProductosResponse")]
        CapaLogicaNegocios.ServicioMasterBikes.Cl_Producto[] obtenerProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/obtenerProductos", ReplyAction="http://tempuri.org/IServicio/obtenerProductosResponse")]
        System.Threading.Tasks.Task<CapaLogicaNegocios.ServicioMasterBikes.Cl_Producto[]> obtenerProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/obtenerMunicipalidades", ReplyAction="http://tempuri.org/IServicio/obtenerMunicipalidadesResponse")]
        CapaLogicaNegocios.ServicioMasterBikes.Cl_Municipalidad[] obtenerMunicipalidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/obtenerMunicipalidades", ReplyAction="http://tempuri.org/IServicio/obtenerMunicipalidadesResponse")]
        System.Threading.Tasks.Task<CapaLogicaNegocios.ServicioMasterBikes.Cl_Municipalidad[]> obtenerMunicipalidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/obtenerConvenio", ReplyAction="http://tempuri.org/IServicio/obtenerConvenioResponse")]
        int obtenerConvenio(string municipalidad, string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/obtenerConvenio", ReplyAction="http://tempuri.org/IServicio/obtenerConvenioResponse")]
        System.Threading.Tasks.Task<int> obtenerConvenioAsync(string municipalidad, string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/guardarImagen", ReplyAction="http://tempuri.org/IServicio/guardarImagenResponse")]
        bool guardarImagen(byte[] imagen, string nombreArchivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/guardarImagen", ReplyAction="http://tempuri.org/IServicio/guardarImagenResponse")]
        System.Threading.Tasks.Task<bool> guardarImagenAsync(byte[] imagen, string nombreArchivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/obtenerStock", ReplyAction="http://tempuri.org/IServicio/obtenerStockResponse")]
        int obtenerStock(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/obtenerStock", ReplyAction="http://tempuri.org/IServicio/obtenerStockResponse")]
        System.Threading.Tasks.Task<int> obtenerStockAsync(int idProducto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : CapaLogicaNegocios.ServicioMasterBikes.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<CapaLogicaNegocios.ServicioMasterBikes.IServicio>, CapaLogicaNegocios.ServicioMasterBikes.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] ImgToByteArray(string ruta) {
            return base.Channel.ImgToByteArray(ruta);
        }
        
        public System.Threading.Tasks.Task<byte[]> ImgToByteArrayAsync(string ruta) {
            return base.Channel.ImgToByteArrayAsync(ruta);
        }
        
        public CapaLogicaNegocios.ServicioMasterBikes.Cl_Producto[] obtenerProdProv() {
            return base.Channel.obtenerProdProv();
        }
        
        public System.Threading.Tasks.Task<CapaLogicaNegocios.ServicioMasterBikes.Cl_Producto[]> obtenerProdProvAsync() {
            return base.Channel.obtenerProdProvAsync();
        }
        
        public CapaLogicaNegocios.ServicioMasterBikes.Cl_Producto[] obtenerProductos() {
            return base.Channel.obtenerProductos();
        }
        
        public System.Threading.Tasks.Task<CapaLogicaNegocios.ServicioMasterBikes.Cl_Producto[]> obtenerProductosAsync() {
            return base.Channel.obtenerProductosAsync();
        }
        
        public CapaLogicaNegocios.ServicioMasterBikes.Cl_Municipalidad[] obtenerMunicipalidades() {
            return base.Channel.obtenerMunicipalidades();
        }
        
        public System.Threading.Tasks.Task<CapaLogicaNegocios.ServicioMasterBikes.Cl_Municipalidad[]> obtenerMunicipalidadesAsync() {
            return base.Channel.obtenerMunicipalidadesAsync();
        }
        
        public int obtenerConvenio(string municipalidad, string rut) {
            return base.Channel.obtenerConvenio(municipalidad, rut);
        }
        
        public System.Threading.Tasks.Task<int> obtenerConvenioAsync(string municipalidad, string rut) {
            return base.Channel.obtenerConvenioAsync(municipalidad, rut);
        }
        
        public bool guardarImagen(byte[] imagen, string nombreArchivo) {
            return base.Channel.guardarImagen(imagen, nombreArchivo);
        }
        
        public System.Threading.Tasks.Task<bool> guardarImagenAsync(byte[] imagen, string nombreArchivo) {
            return base.Channel.guardarImagenAsync(imagen, nombreArchivo);
        }
        
        public int obtenerStock(int idProducto) {
            return base.Channel.obtenerStock(idProducto);
        }
        
        public System.Threading.Tasks.Task<int> obtenerStockAsync(int idProducto) {
            return base.Channel.obtenerStockAsync(idProducto);
        }
    }
}
